### ISSUE TITLE
[tags] Platform list is not sorted in alphabetical order

### ISSUE THREAD

**Issue by circlesabound** [unswpcsoc/pcsocgo#1]
Severity: Low

Repro steps: 
1. List tag platforms with `!tags platforms`

Actual results: Platforms beginning with a capital letter appear before platforms beginning with a lowercase letter

Expected results: Platforms are sorted in alphabetical order

Image:

![image](https://user-images.githubusercontent.com/1893644/80268967-212b1a00-86ef-11ea-91eb-a2854f2f05f3.png)

**Comment by VineBalloon** [comment]
Fixed 
![Screenshot_2020-04-28-14-33-54](https://user-images.githubusercontent.com/28817893/80447643-4f159600-895d-11ea-86b7-0035e00556aa.png)
